baseurl = "https://bths-solar-car.github.io/blog/"
languageCode = "en-us"
title = "BlueBird Blog"
theme = "github-style"
googleAnalytics = ""
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  author = "Project BlueBird"
  description = "The pessimist sees difficulty in every opportunity"
  instagram = "bths.solar"
  # email = "email"
  github = "BTHS SCT"
  url = "https://bths-solar-car.github.io/"
  keywords = "Solar, Solar Car, Car, Blue, BlueBird, Blue Bird, Project, Solar Car Challenge, BTHS, Brooklyn Technical, High School, High, School, blog, electric car"
  rss = false
  lastmod = true
  favicon = "/images/github.png"
  location = "Brooklyn, NY"

[frontmatter]
  lastmod = ["lastmod", ":fileModTime", ":default"]
